### ISSUE TITLE
Improve the REST api

### ISSUE THREAD

**Issue by masteret** [tweetcity/cs373-idb#45]
Let it be more restful
Please adhere to REST-naming practices when designing your api. Here are some quick and dirty REST tips and examples:

https://github.com/WhiteHouse/api-standards#general-guidelines-for-restful-urls
https://github.com/WhiteHouse/api-standards#good-url-examples
https://github.com/WhiteHouse/api-standards#bad-url-examples

Also check Piazza post

**Comment by cschwendiman** [comment]
made all resources plural, and used subresource notation (/tweets/1/hashtags/ instead of /hashtagsByTweet/1/)
